server:
  port: 8081
spring:
  application:
    name: huser
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-lpvk70oq.sql.tencentcdb.com:21186/house?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Zzh320281
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect